In [7]:
import pandas as pd
import numpy as np

def calculate_volatility_percent(df, period=365*24*60):
    """
    Calculate the annualized volatility percentage of a given DataFrame.

    Args:
        df (pd.DataFrame): DataFrame with columns ['Open', 'High', 'Low', 'Close'].
        period (int): Number of periods in a year (default is 525600 for 1-minute data).

    Returns:
        float: Annualized volatility percentage.
    """
    if not all(col in df.columns for col in ['Open', 'High', 'Low', 'Close']):
        raise ValueError("DataFrame must contain columns ['Open', 'High', 'Low', 'Close']")

    # Calculate log returns
    df['log_return'] = np.log(df['Close'] / df['Close'].shift(1))

    # Drop NaN values resulting from the shift operation
    df = df.dropna()

    # Calculate the standard deviation of log returns (daily volatility)
    daily_volatility = df['log_return'].std()

    # Annualize the volatility
    annualized_volatility = daily_volatility * np.sqrt(period)

    # Convert to percentage
    return annualized_volatility * 100

def rank_volatility(dataframes, period=365*24*60):
    """
    Rank multiple dataframes by their volatility percentage.

    Args:
        dataframes (dict): Dictionary where keys are token names and values are DataFrames.
        period (int): Number of periods in a year (default is 525600 for 1-minute data).

    Returns:
        pd.DataFrame: DataFrame with tokens ranked by their volatility.
    """
    results = []

    for token, df in dataframes.items():
        try:
            volatility = calculate_volatility_percent(df, period)
            results.append({"Token": token, "Volatility (%)": volatility})
        except Exception as e:
            print(f"Error calculating volatility for {token}: {e}")

    # Create a DataFrame and sort by volatility in descending order
    volatility_df = pd.DataFrame(results)
    return volatility_df.sort_values(by="Volatility (%)", ascending=False)

# Example usage:
# Suppose you have multiple DataFrames for different tokens in a dictionary

In [8]:
data = {}

granularity = '1m'
pairs = ['DOTUSDT','DOGEUSDT','ADAUSDT','XRPUSDT','TRXUSDT','XLMUSDT','APTUSDT','VIDTUSDT','BTCUSDT',
         'ETHUSDT','AVAXUSDT','BNBUSDT','LTCUSDT','LINKUSDT',
         'BCHUSDT','EOSUSDT','ETCUSDT','DASHUSDT','ALGOUSDT','SANDUSDT',
         'ARUSDT', 'INJUSDT', 'MASKUSDT', 'CELOUSDT', 'BANDUSDT', 'ALPHAUSDT', 'PERPUSDT',
         'ACHUSDT', 'CHRUSDT', 'BELUSDT']

for p in pairs:
    data[p] = pd.read_pickle(f"crypto/{p}_{granularity}.pkl")

In [9]:
ranked_volatility = rank_volatility(data)

In [10]:
rank = ranked_volatility

In [11]:
rank

        Token  Volatility (%)
7    VIDTUSDT      136.943965
27    ACHUSDT      131.718939
21    INJUSDT      125.938248
26   PERPUSDT      125.524604
20     ARUSDT      123.403708
25  ALPHAUSDT      121.217925
29    BELUSDT      117.442016
6     APTUSDT      112.875462
23   CELOUSDT      112.301685
22   MASKUSDT      108.804010
28    CHRUSDT      106.826348
10   AVAXUSDT      104.456251
24   BANDUSDT      104.035169
1    DOGEUSDT      100.214975
11    BNBUSDT       92.487231
0     DOTUSDT       90.898566
19   SANDUSDT       89.544970
18   ALGOUSDT       89.391736
15    EOSUSDT       88.639827
14    BCHUSDT       87.569426
9     ETHUSDT       86.931159
2     ADAUSDT       86.821159
5     XLMUSDT       84.084122
13   LINKUSDT       81.904566
17   DASHUSDT       81.622473
12    LTCUSDT       81.483928
3     XRPUSDT       80.644738
16    ETCUSDT       80.294237
8     BTCUSDT       70.811099
4     TRXUSDT       53.900839